- name: Checking whether roboshop user exists
  ansible.builtin.command: id roboshop
  register: out
  ignore_errors: true

- when: out.rc != 0
  name: add roboshop user
  ansible.builtin.user:
    name: roboshop

- name: checking the app directory
  ansible.builtin.stat: 
    path: /app
  register: directory

- name: Printing the stat
  ansible.builtin.debug:
    msg: "Output is : {{directory}}"

- when: directory.stat.exists == False
  name: Create app directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download the {{component}} artifact
  ansible.builtin.get_url:
    url: "https://roboshop-builds.s3.amazonaws.com/{{component}}.zip"
    dest: /tmp

- name: Extracting the {{component}} artifact
  ansible.builtin.unarchive:
    src: "/tmp/{{component}}.zip"
    dest: /app
    remote_src: yes